NEW Create action
silverstripe/gha-auto-tag pull request #1
Opened 2022-05-30 22:58 UTC by emteknetnz

2022-05-31 12:00 UTC, emteknetnz commented on .github/workflows/auto-tag.yml
> +          ref: ${{ github.ref }}
Remove passing in ref + sha

2022-05-31 12:01 UTC, emteknetnz commented on README.md
> +          ref: ${{ github.ref }}
Remove passing in ref + sha

2022-05-31 12:01 UTC, emteknetnz commented on action.yml
> +        SHA: ${{ inputs.sha }}
not nee to validate sha, though do need to validate ${{ github.ref }}

2022-05-31 12:01 UTC, emteknetnz commented on action.yml
> +inputs:
Remove inputs

2022-05-31 12:02 UTC, emteknetnz commented on action.yml
> +        sha: ${{ github.sha }}
Remove sha

2022-06-03 00:00 UTC, GuySartorelli requested changes

2022-06-03 00:00 UTC, ChloeSartorelli commented on action.yml
> +        [[ $TAG =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]
```suggestion
    - name: Generate tag name
      id: generate_tag_name
      shell: bash
      env:
        REF: ${{ github.ref }}
      run: |
        # refs/tags/0.1.23 => 0.1.23
        TAG=$(echo $REF | cut -c 11-)
        if ! [[ "$TAG" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          echo "Invalid semver tag $TAG"
          exit 1
        fi
        echo "Valid semver tag $TAG"
```

I don't think it's useful to have the validation step separate - it just results in code duplication.

2022-06-03 00:00 UTC, ChloeSartorelli commented on .github/workflows/auto-tag.yml
> +        uses: silverstripe/gha-auto-tag@main
We should declare the expected tag here shouldn't we? i.e. `@v1`?
Or will that be done (on all repositories) as a separate PR after this first load are merged (in a new `1` branch, prior to the `1.0.0` tag being created)?

2022-06-03 00:00 UTC, ChloeSartorelli commented on action.yml
> +      uses: silverstripe/gha-tag-release@main
Same question as above regarding `@main` vs `@v1`

2022-06-03 00:00 UTC, ChloeSartorelli commented on README.md
> +
```suggestion

This action has no configuration or inputs - just add the following workflow verbatim.

```

2022-06-03 00:03 UTC, emteknetnz commented on .github/workflows/auto-tag.yml
> +        uses: silverstripe/gha-auto-tag@main
> Or will that be done (on all repositories) as a separate PR after this first load are merged (in a new 1 branch, prior to the 1.0.0 tag being created)?

Yes - follow up PRs once everything is merged

2022-06-03 00:20 UTC, emteknetnz commented on action.yml
> +      uses: silverstripe/gha-tag-release@main
Same answer as above - we'll use follow up PR's to update

2022-06-07 02:25 UTC, emteknetnz commented on README.md
> +
Added

2022-06-07 02:28 UTC, emteknetnz commented on action.yml
> +        [[ $TAG =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]
Have combined steps

2022-06-09 04:46 UTC, GuySartorelli approved these changes
Looks good
Please give me permissions necessary to merge :p

2022-06-09 04:52 UTC, GuySartorelli requested changes
Very minor formatting problem. It's the only place I've seen where there's no new line before a step.

2022-06-09 04:52 UTC, GuySartorelli commented on action.yml
> +    - name: Generate tag name
```suggestion

    - name: Generate tag name
```

2022-06-09 05:32 UTC, emteknetnz commented on action.yml
> +    - name: Generate tag name
Done

2022-06-09 05:33 UTC, GuySartorelli approved these changes
Looks good

2022-06-09 05:33 UTC, merged